#! /bin/sh


$HOME/.config/bspwm/autostart.sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5 

bspc config border_width         2
bspc config window_gap          12
bspc config top_padding 	 3
bspc config right_padding 	 3
bspc config bottom_padding 	 3
bspc config left_padding	 3

bspc config focused_border_color "#00ccff"
bspc config normal_border_color "#ccf5ff"
bspc copnfig focus_follows_pointer true


bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

